### PR TITLE
Final fixes to merge

### PR DESCRIPTION
**Pull request by v-bhmakwn**
Final fixes to merge

### CODE REVIEW

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-ja-jp-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-ja-jp-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201808240006327809-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vBrRam9ujhWkhf9Up4%2Fl4lhsWbOXrxZKbJdQ78vfELs%3D&st=2018-08-24T00%3A03%3A38Z&se=2018-09-24T00%3A08%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-ja-jp-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-ja-jp-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201808240016352486-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=w7I6%2Bla1Y6W%2F9sTy5i7Ca5U4A0vEualdToxTET%2BGPxA%3D&st=2018-08-24T00%3A13%3A39Z&se=2018-09-24T00%3A18%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-ja-jp-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-ja-jp-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201808240016433104-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HtY4PHzQnyxgooD2z2wff49X05gwRsnqqzPsPcJ0rzw%3D&st=2018-08-24T00%3A15%3A46Z&se=2018-09-24T00%3A20%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-ja-jp-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-ja-jp-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201808240024272074-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oywBNDVkw7xkDb%2BT%2FoxZVoSqgOUM9MUbQS5%2FH8GnPSs%3D&st=2018-08-24T00%3A21%3A42Z&se=2018-09-24T00%3A26%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-ja-jp-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-ja-jp-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201808240027162450-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=be5FOuwm22d1PXRhWK4WG328xDkYLBGqxqqt8XPsx2g%3D&st=2018-08-24T00%3A24%3A15Z&se=2018-09-24T00%3A29%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-ja-jp-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-ja-jp-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201808240027540216-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=25g4yUSu4FAXwqTPIGH8Mof%2BNk6fIDzsdpjh2I0oHYE%3D&st=2018-08-24T00%3A26%3A43Z&se=2018-09-24T00%3A31%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-ja-jp-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-ja-jp-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201808240034431088-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ztVkmU4gzXyj4raP9Qm1VDMlR87BWglOgx1sRiHswjs%3D&st=2018-08-24T00%3A31%3A56Z&se=2018-09-24T00%3A36%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-ja-jp-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-bhmakwn/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/Final-Fixes/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-ja-jp-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201808240042013390-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8IAKHgp%2Fdn2D3fiv1bH7ipNB4PxSEB%2B4GeIEw5shFjE%3D&st=2018-08-24T00%3A39%3A05Z&se=2018-09-24T00%3A44%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Review by DanMSFT — APPROVED** [review]
I am concerned that the nested Alert boxes will be an issue, but willing to see how the build makes this look.

**Pull request merged**
